<TestLog><TestSuite name="test_suite"><TestCase name="fs_test_directory_reader" file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="16"><Error file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="24"><![CDATA[check paths.size() == 7 has failed [12 != 7]]]></Error><Error file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="25"><![CDATA[check paths[0] == "./untitled.cbp" has failed ["./zmq_test_client" != ./untitled.cbp]]]></Error><TestingTime>1047</TestingTime></TestCase><TestCase name="curl_test_easy" file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="28"><Info file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="39"><![CDATA[check sz > 0 has passed]]></Info><TestingTime>103061</TestingTime></TestCase><TestCase name="net_test_endpoint_lookup" file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="42"><Info file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="55"><![CDATA[check epvec.size() >= 2 has passed]]></Info><Info file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="56"><![CDATA[check epvec[0].address().to_string() == "34.208.114.108" has passed]]></Info><Info file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="57"><![CDATA[check epvec[1].address().to_string() == "54.202.218.164" has passed]]></Info><TestingTime>827</TestingTime></TestCase><TestCase name="util_test_hexdump" file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="60"><Info file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="66"><![CDATA[check libnj::fs::readfile(filename_in,data_in) > 0 has passed]]></Info><Info file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="72"><![CDATA[check libnj::fs::readfile(filename_out,data_out) > 0 has passed]]></Info><Info file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="77"><![CDATA[check data_out == dump_out has passed]]></Info><Info file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="81"><![CDATA[check 'exception "std::runtime_error" raised as expected' has passed]]></Info><TestingTime>1133</TestingTime></TestCase><TestCase name="util_test_tokenizer" file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="84"><Info file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="90"><![CDATA[check tok == "1" has passed]]></Info><Info file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="91"><![CDATA[check tok == "2" has passed]]></Info><Info file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="92"><![CDATA[check tok == "3" has passed]]></Info><Info file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="93"><![CDATA[check tok == "4" has passed]]></Info><Info file="/Users/nverenin/git/cpp-examples/tests/test_suite.cpp" line="94"><![CDATA[check t.next(tok) == false has passed]]></Info><TestingTime>170</TestingTime></TestCase></TestSuite></TestLog>